---
- name: Create script for registration from j2 template
  ansible.builtin.template:
    src: "gitlab-runner-register.j2"
    dest: "gitlab-runner-register"
    owner: root
    group: root
    mode: 0755
  when:
    - domain_name is defined
    - registration_token is defined

- name: Register GitLab Runner
  ansible.builtin.shell: "./gitlab-runner-register"
