---
- name: Add apt repository for GitLab Runner
  ansible.builtin.shell: "curl -L \"https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh\" | sudo bash"
  args:
    executable: /bin/bash

- name: Update apt and install GitLab Runner
  ansible.builtin.apt:
    pkg:
      - gitlab-runner
    state: present
    update_cache: true
