---
- name: Create a directory /etc/prometheus if it does not exist
  ansible.builtin.file:
    path: "/etc/prometheus"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create /etc/prometheus/prometheus.yml.append file from j2 template
  ansible.builtin.template:
    src: "prometheus.yml.append.j2"
    dest: "/etc/prometheus/prometheus.yml.{{ monitoring_target }}.append"
    owner: root
    group: root
    mode: 0644
