#!/usr/bin/env bash

DNS_ZONE_NAME=$1
DNS_ZONE_RECORD=$2
DNS_ZONE_RECORD_TYPE=$3
IP_ADDR=$4

if [ -t $DNS_ZONE_NAME ]
then
  echo 'Need dns zone name in 1 arg'
  exit 1
fi

if [ -t $DNS_ZONE_RECORD ]
then
  echo 'Need dns zone record in 2 arg'
  exit 1
fi

if [ -t $DNS_ZONE_RECORD_TYPE ]
then
  echo 'Need dns record type in 3 arg'
  exit 1
fi

if [ -t $IP_ADDR ]
then
  echo 'Need ip address in 4 arg'
  exit 1
fi

yc dns zone add-records --name $DNS_ZONE_NAME --record "$DNS_ZONE_RECORD 300 $DNS_ZONE_RECORD_TYPE $IP_ADDR" 2>/dev/null

yc dns zone replace-records --name $DNS_ZONE_NAME --record "$DNS_ZONE_RECORD 300 $DNS_ZONE_RECORD_TYPE $IP_ADDR" 2>/dev/null

exit 0