resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    ngnix

    [ngnix]
    ${local.dns_zone} ansible_host=${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}

    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.nginx
  ]
}
