version: '2.1'

services:

  nginx:
    image: nginx:1.22
    container_name: nginx
    network_mode: "host"
    volumes:
      - /opt/nginx/templates:/etc/nginx/templates
      - /usr/share/nginx/html:/usr/share/nginx/html
    restart: always
