---
- name: Add Grafana apt key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add apt Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Update apt and install Grafana
  ansible.builtin.apt:
    pkg:
      - grafana
    state: present
    update_cache: true
