---
- name: Update apt and install MySQL server
  ansible.builtin.apt:
    pkg:
      - mysql-server
    state: present
    update_cache: true

- name: Make sure pymysql is present
  ansible.builtin.pip:
    name: pymysql
    state: present

- name: Install percona repo deb package
  ansible.builtin.apt:
    deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_lsb.codename|lower }}_all.deb"

- name: Configure percona repo
  ansible.builtin.shell: "percona-release enable-only tools release"
  args:
    executable: /bin/bash

- name: Update apt and Percona XtraBackup
  ansible.builtin.apt:
    pkg:
      - percona-xtrabackup-80
      - qpress
    state: present
    update_cache: true
