---
- name: Update apt and install MySQL server
  ansible.builtin.apt:
    pkg:
      - mysql-server
    state: present
    update_cache: true

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present
