---
- name: Install of requirements tools
  hosts: monitoring
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.install_tools

- name: Node_exporter install
  hosts: nodes
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.node_exporter_install

- name: Alertmanager install
  hosts: monitoring
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.alertmanager_install

- name: Prometheus install
  hosts: monitoring
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.prometheus_install

- name: Grafana install
  hosts: monitoring
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.grafana_install
