---
- name: MySQL create database '{{ database_name }}' and user, if defined
  hosts: mysql
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.mysql_config
    when: (bind-address or server_id or log_bin or binlog_do_db or relay-log) is defined
