---
- name: MySQL config
  hosts: "{{ mysql_hosts }}"
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.mysql_config

- name: MySQL restart
  hosts: "{{ mysql_hosts }}"
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.mysql_restart
