---
- name: Install of Requrements Tools
  hosts: nodes
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.docker_install

- name: Docker-compose up
  hosts: nodes
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: malzew.docker_compose_up
    vars:
      docker_compose_src_dir: files/reverse_proxy
