---
- name: "Create MySQL server config file from j2 template"
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: "{{ conf_file }}"
    owner: mysql
    group: mysql
    mode: 0644
  when: conf_file is defined and bind_address is defined and server_id is defined and binlog_do_db is defined
