---
- name: copy docker-compose
  ansible.builtin.copy:
    src: "{{ docker_compose_src_dir }}/"
    dest: "{{ docker_compose_src_dir }}"
    mode: 0644
  when: docker_compose_src_dir is defined

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ docker_compose_src_dir }}"
  register: output
  when: docker_compose_src_dir is defined
