---
- name: Create a new database '{{ database_name }}'
  community.mysql.mysql_db:
    name: "{{ database_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: database_name is defined

- name: Create database user '{{ database_user }}' with password and all database privileges
  community.mysql.mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: database_user is defined and database_password is defined
